Header
full-profane/itsy pull request #1
Opened 2021-01-22 14:47 UTC by full-profane

![image](https://user-images.githubusercontent.com/61840948/105505368-8a1cde00-5cd1-11eb-9f92-86e0fc676e4a.png)

2021-01-22 17:49 UTC, max-si-m requested changes

2021-01-22 17:49 UTC, max-si-m commented on itsy.css
> +}
add spaces after bracket `}`
```suggestion
}

```

2021-01-22 17:49 UTC, max-si-m commented on itsy.css
> +  background: url(img/lead.jpg);
not sure that background image should be in header tag, it doesn't related to that.

2021-01-22 17:49 UTC, max-si-m commented on itsy.css
> +
```suggestion
```

2021-01-22 17:49 UTC, max-si-m commented on itsy.css
> +
```suggestion
```

2021-01-22 17:49 UTC, max-si-m commented on itsy.css
> +  padding: 10px 30px;
looks a little bit better

```suggestion
  padding: 20px;
```

2021-01-22 17:49 UTC, max-si-m commented on itsy.css
> +
and font color should be gray, not a black

2021-01-22 17:49 UTC, max-si-m commented on itsy.css
> +  float: left;
please, try to change that to flexbox. We're trying to learn something new here.

2021-01-22 17:49 UTC, max-si-m commented on itsy.css
> +  float: left;
And add pink hover effect, as you saw during demo.

2021-01-22 17:49 UTC, max-si-m commented on itsy.css
> +  color: #e68a8a;
it looks more as active state of icon. Please change css selector to `.active` and use that instead of `icon__search`

2021-01-22 17:49 UTC, max-si-m commented on itsy.css
> +body {
Please move file into `styles` folder

2021-01-22 17:49 UTC, max-si-m commented on itsy.css
> +  margin: 0px;
Please change to flexboxes, use margin left if you want but better will be better to use flex grow/shrink and so on.

2021-01-22 17:49 UTC, max-si-m commented on itsy.css
> +  margin: 0px;
redundant

2021-01-22 17:49 UTC, max-si-m commented on itsy.css
> +  font-family: 'Amatic SC', 'Heveltica Neue', Arial, sans-serif;
please define font-family clasess and reuse them, like 
`.amatic { font-family: 'Amatic SC', 'Heveltica Neue', Arial, sans-serif; } `

2021-01-22 17:49 UTC, max-si-m commented on itsy.html
> +      <div class="header-top">
fix indentation

2021-01-22 17:49 UTC, max-si-m commented on itsy.html
> +        <div class="home-text">
please add `hero-page` container and put here there :)

2021-01-22 17:49 UTC, max-si-m commented on itsy.html
> +        <div class="header-arrow"> &#748;</div>
use font awesome for arrow

2021-01-22 17:49 UTC, max-si-m commented on itsy.css
> +  text-transform: uppercase;
👍

2021-01-22 17:55 UTC, full-profane commented on itsy.css
> +  padding: 10px 30px;
not , i like my varriant

2021-01-23 09:46 UTC, max-si-m requested changes

2021-01-23 09:46 UTC, max-si-m commented on itsy.html
> +  <div class="home">
please move amatic to the container div, as there is amatic everywhere.

2021-01-23 09:46 UTC, max-si-m commented on itsy.html
> +      <div class="header__logo amatic">itsy</div>
redundant .amatic

2021-01-23 09:46 UTC, max-si-m commented on itsy.html
> +          <div class="header__list">home</div>
seems better `.header-menu__item` or `.header__menu--item`, you khow how it should be.

2021-01-23 09:46 UTC, max-si-m commented on itsy.html
> +        <div class="header-menu amatic">
please, fix indentation

2021-01-23 09:46 UTC, max-si-m commented on itsy.html
> +      <div class="home-text amatic">
fix indentation

2021-01-23 09:46 UTC, max-si-m commented on styles/itsy.css
> +}
new line after }
```suggestion
}

```

2021-01-23 09:46 UTC, max-si-m commented on styles/itsy.css
> +    font-family: 'Amatic SC', 'Heveltica Neue', Arial, sans-serif;
```suggestion
  font-family: 'Amatic SC', 'Heveltica Neue', Arial, sans-serif;
```

2021-01-23 09:46 UTC, max-si-m commented on styles/itsy.css
> +  color: #e68a8a;
please, identify classes via comma to reduce duplication of styles.
`.some-class, .b-class {color: red}`

2021-01-23 10:18 UTC, max-si-m requested changes

2021-01-23 10:18 UTC, max-si-m commented on itsy.html
> +    <div class="home-text amatic">
```suggestion
    <div class="home-text">
```

2021-01-23 10:18 UTC, max-si-m commented on styles/itsy.css
> +.header-menu__item:hover, .header__icon:hover {
```suggestion
.active, .header-menu__item:hover, .header__icon:hover {
```

2021-01-23 10:18 UTC, max-si-m commented on styles/itsy.css
> +.active {
please, delete

2021-01-23 10:24 UTC, max-si-m approved these changes

2021-01-23 10:28 UTC, merged